version: "3.4"
services:
  mev-boost.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.3.2
    volumes:
      - "data:/var/lib/mev-boost"
    environment:
      NETWORK: mainnet
      ADDITIONAL_RELAYS: ""
      RELAY_MODE: Non-compliant
      ONLY_USER_RELAYS: Use pre-defined relays
    image: "mev-boost.public.dappnode.eth:0.2.4"
    restart: unless-stopped
volumes:
  data: {}
